### ISSUE TITLE
Don't compare the relative order of timestamps

### ISSUE THREAD

**Issue by asomers** [musikid/pjdfstest#100]
The system clock, used for file timestamps, isn't guaranteed to be monotonic.  So there's no guarantee that a file's timestamp "after" an operation will be greater than its timestamp "before" the operation.  Instead, the only thing we can rely on is that it will be changed.

The original pjdfstest assumes a monotonic system clock and compares timestamp ordering.  So for the GSoC rewrite, let's be bug-compatible.  Afterwards we can fix this issue.

**Comment by musikid** [comment]
FWIW, I use an inequality check for the new time assertion API. Should I revert to an ordering comparison?

**Comment by asomers** [comment]
Oh, maybe I was looking at an old branch.  No need to revert.

**Comment by musikid** [comment]
I will let this issue for the existing tests which needs to be rewritten.
