### ISSUE TITLE
Rewrite granular tests

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#14]
# granular

This issue tracks the progress of the rewrite for the granular folder.

- [ ] 00.t | NFSv4 granular permissions checking - WRITE_DATA vs APPEND_DATA on directories
- [ ] 01.t | NFSv4 granular permissions checking - ACL_READ_ATTRIBUTES and ACL_WRITE_ATTRIBUTES
- [ ] 02.t | NFSv4 granular permissions checking - ACL_READ_ACL and ACL_WRITE_ACL
- [ ] 03.t | NFSv4 granular permissions checking - DELETE and DELETE_CHILD
- [ ] 04.t | NFSv4 granular permissions checking - ACL_WRITE_OWNER
- [ ] 05.t | NFSv4 granular permissions checking - DELETE and DELETE_CHILD with directories
- [ ] 06.t | NFSv4 granular permissions checking - setuid and setgid are cleared when non-owner calls chown

**Comment by asomers** [comment]
So this is harder than I expected.  I've got about a third of the tests converted, but I'm running into several problems:

- The tests are highly interdependent, more so than other files in pjdfstest, with overlapping conditions and assertions.  With enough time, I could untangle this.
- The tests are very incomplete.  NFSv4 ACLs are hella complicated, and pjdfstest only scratches the surface.
- The kernel's behavior seems to be wrong in some cases, and the tests are programmed to expect the misbehavior.
- There is no written standard for NFSv4 ACLs, so it's hard to know exactly what the correct behavior is.
- There are some additional ACL tests in the FreeBSD base system in the tests/sys/acl directory, but their organization is even worse than pjdfstest, and it's hard to tell how complete they are.
- There are also some ACL tests in the ZFS test suite, but they need a lot of work too.  Also, the ZFS test suite is super slow.

I think the best we can shoot for is to convert the existing tests that happen to work, and perhaps propose a future GSoC project to finish a complete NFSv4 ACL test suite.

**Comment by asomers** [comment]
Completed by #106 .  Except as I described in the PR, I did not convert tests that work with combinations of DELETE and DELETE_CHILD, because such behavior is file system-dependent and the existing tests were of low quality.
