### ISSUE TITLE
Rewrite mkfifo tests

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#17]
# mkfifo

This issue tracks the progress of the rewrite for the mkfifo folder.

- [x] 00.t | mkfifo creates fifo files
- [x] 01.t | mkfifo returns ENOTDIR if a component of the path prefix is not a directory
- [x] 02.t | mkfifo returns ENAMETOOLONG if a component of a pathname exceeded {NAME_MAX} characters
- [x] 03.t | mkfifo returns ENAMETOOLONG if an entire path name exceeded {PATH_MAX} characters
- [x] 04.t | mkfifo returns ENOENT if a component of the path prefix does not exist
- [x] 05.t | mkfifo returns EACCES when search permission is denied for a component of the path prefix
- [x] 06.t | mkfifo returns EACCES when write permission is denied on the parent directory of the file to be created
- [x] 07.t | mkfifo returns ELOOP if too many symbolic links were encountered in translating the pathname
- [x] 08.t | mkfifo returns EROFS if the named file resides on a read-only file system
- [x] 09.t | mkfifo returns EEXIST if the named file exists
- [x] 10.t | mkfifo returns EPERM if the parent directory of the file to be created has its immutable flag set
- [x] 11.t | mkfifo returns ENOSPC if there are no free inodes on the file system on which the file is being created
- [x] 12.t | mkfifo returns EFAULT if the path argument points outside the process's allocated address space

**Comment by asomers** [comment]
I've rewritten some of these tests , but none of them are really fifo-specific.  They could all be implemented generically, so this issue is blocked by #67
