### ISSUE TITLE
Rewrite utimensat tests

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#26]
# utimensat

This issue tracks the progress of the rewrite for the utimensat folder.

- [ ] 00.t | utimensat changes timestamps on any type of file
- [ ] 01.t | utimensat with UTIME_NOW will set the will set typestamps to now
- [ ] 02.t | utimensat with UTIME_OMIT will leave the time unchanged
- [ ] 03.t | utimensat can update birthtimes
- [ ] 04.t | utimensat can set mtime < atime or vice versa
- [ ] 05.t | utimensat can follow symlinks
- [ ] 06.t | utimensat with UTIME_NOW will work if the caller has write permission
- [ ] 07.t | utimensat will work if the caller is the owner or root
- [ ] 08.t | utimensat can set timestamps with subsecond precision
- [ ] 09.t | utimensat is y2038 compliant

**Comment by asomers** [comment]
Mind if I take this one?

**Comment by musikid** [comment]
Of course, no problem! Is the documentation clear enough?

**Comment by asomers** [comment]
Clear enough to start at least.  I mostly want to convert a few tests just to teach myself how.  Maybe the exercise will reveal some bugs too.
