### ISSUE TITLE
Build failure on FreeBSD

### ISSUE THREAD

**Issue by asomers** [musikid/pjdfstest#3]
I'm guessing you've been developing on Linux so far, because I notice that the project doesn't currently build on FreeBSD.  I see two general types of error:
* `nix::sys::stat::makedev` is only defined on Linux
* `mode_t` is 32-bit on Linux, but 16-bits on FreeBSD.

**Comment by musikid** [comment]
It now works on FreeBSD, although I'm not sure of how to fix the `mode_t` problem.
I've also removed the major/minor numbers for `mknod` as I am unsure of how meaningful they are today, given that FreeBSD doesn't really use them now.

**Comment by asomers** [comment]
I suggest using the `mode_t` type exported by libc and reexported by Nix, like this:
```rust
const FILE_PERMS: nix::sys::stat::mode_t = 0o777;
```

**Comment by musikid** [comment]
Thanks, implemented with d7db90d9bf458c82df97cfba05723ba0bdefa53d!
