### ISSUE TITLE
Automatic test case collection

### ISSUE THREAD

**Issue by asomers** [musikid/pjdfstest#30]
In the beginning you asked me if you should use linker sections to implement automatic test case collection.  I said no, because I was worried about schedule.  But that was before I knew about the [inventory](https://github.com/dtolnay/inventory) crate, which makes it super-easy!  I think we should use it.  Still, it wasn't part of your proposal to include it, so I'll prepare a PR.

**Comment by musikid** [comment]
Yes, I linked it on the [issue](https://github.com/pjd/pjdfstest/issues/59#issuecomment-1076304233) along with linkme, when I was talking about linker sections and code before main!
