### ISSUE TITLE
07.t | chmod returns EPERM if the operation would change the ownership, but the effective user ID is not the super-user

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#66]
In the original test suite, the file `${n1}/${n2}` is created:
https://github.com/musikid/pjdfstest/blob/bde2b19823caaed9489e193597ce047c803bca36/tests/chmod/07.t#L37
But then, `${n2}` without leading folder `${n1}` is used:
https://github.com/musikid/pjdfstest/blob/bde2b19823caaed9489e193597ce047c803bca36/tests/chmod/07.t#L38

Is this a typo, or am I missing something?

**Comment by asomers** [comment]
No, that looks correct.  It should create a $[n1}/${n3} link pointing to ${n2} .  The symlink command can be confusing when operating in a distant directory.

**Comment by musikid** [comment]
Oh, thanks, I got it, symlink is confusing indeed!
