### ISSUE TITLE
Generify errno tests

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#67]
Most errno tests are pratically the same, therefore a set of assertion helpers would drastically reduce the amount of code to rewrite.
The most obvious example is ELOOP.

**Comment by asomers** [comment]
How about if we create a separate directory called `src/tests/errors` for common error cases and put test cases in there.  Then we can leverage the existing support for multiple filetypes, like this?
```rust
crate::test_case! {
    eloop => [Regular, Dir, Fifo, Block, Char, Socket]
    // mkfifo/07.t
    // mknod/07.t
    // ...
}
fn eloop(&mut TestContext, ft: FileType) {
    ...
}
```

**Comment by musikid** [comment]
That seems good to me, but don't we lose some granularity this way? I'm not sure of how users would prefer to filter the tests, but since multiple syscalls are tested this way, we no longer can filter solely by name, except if we add a new macro form for these tests.

**Comment by asomers** [comment]
We won't be able to filter by name with a syscall, but we'll still be able to filter by filetype, for example you could filter on `::regular` to run all tests for regular files.
Speaking as a file system developer, when I filter tests I almost always run "everything" or "the single test case that just failed".
