### ISSUE TITLE
Provide accurate backtraces for failed tests

### ISSUE THREAD

**Issue by asomers** [musikid/pjdfstest#68]
When a test fails, the runner prints the line where the panic happened, like this:
```
pjdfstest::tests::mkfifo::timestamps	error: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }, located in file src/tests/mod.rs at 74:40
```
If you run with `RUST_BACKTRACE=1`, then the runner still prints that, but it also prints an unhelpful stack trace at program exit, like this:
```
Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/somers/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.58/src/error.rs:81:36
   1: anyhow::private::format_err
             at /home/somers/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.58/src/lib.rs:665:13
   2: pjdfstest::main
             at ./src/main.rs:116:13
...
```
Instead, we should print full stack traces for failed tests, and never print them at program exit.

**Comment by musikid** [comment]
Well, either option can just be documented, and like you said, since it will mostly be used by developers, we should go for the `RUST_BACKTRACE` variable.
