### ISSUE TITLE
Flag's file system dependent behavior

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#70]
Some syscalls don't work when some flags are set on a file, but this behavior is not uniform. For example, when SF_APPEND is applied to a file, it's still possible to change its mode with `chmod` on a ZFS file system, but not on a UFS one.

https://github.com/musikid/pjdfstest/blob/6cb23f752270d94f51ef097c19a27ade91025dae/tests/chmod/08.t#L50

https://github.com/musikid/pjdfstest/blob/6cb23f752270d94f51ef097c19a27ade91025dae/tests/chmod/08.t#L62

**Comment by musikid** [comment]
This could be configured via the configuration file, by adding a map of syscalls which behavior should change with a flag, and specifying which flags should make the syscall fail.

**Comment by musikid** [comment]
It has different sets of tests for each file system, and would change the TAP plan according to the detected file system.

**Comment by asomers** [comment]
Oh, gross.  Yeah, we should either create a feature for that, or else just write the tests so as to accept either behavior.  Here's an example of a similar behavior that's not required by POSIX.
https://github.com/pjd/pjdfstest/pull/35/files
