### ISSUE TITLE
Tests involving memory disks

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#75]
EROFS (and some others like ENOSPC) tests create memory disks to test if the correct error is returned when the syscall is used on this disk. However, these tests are not file system agnostic since they only create UFS partitions (and also ZFS for only one test). It shouldn't be difficult to rewrite these tests, however how should I make them file system agnostic? I'm not sure that the file systems being tested would always be available to create on a memory disk.

[test example](https://github.com/musikid/pjdfstest/blob/master/tests/mkfifo/08.t)

**Comment by asomers** [comment]
Here are some options:
1) In the config file, specify commands to create, mount, and unmount new file systems.  Then execute those commands in the EROFS tests.
2) Provide a separate binary, like pjdfstest-erofs, that just runs tests which need a small file system.  Then the user can invoke them like this:
  * Create a big filesystem
  * run `pjdfstest`
  * Create a tiny filesystem
  * run `pjdfstest-erofs`

Can you think of anything else?

**Comment by musikid** [comment]
I was thinking about implementing the first option, but I wasn't sure that there will be commands to create the file system, thanks.
Also, what should be the size of the created memory disk? Most tests have 512 KB - 1 MB, but it seems that ZFS needs at least 128 MB. Should we make it a mandatory option in the config file?

**Comment by asomers** [comment]
ZFS will flatly refuse to create a disk < 64 MB in size.  With grep, I see the following kinds of tests that need to create new file systems:
* ENOSPC: Needs the test file system to be very small.
* EXDEV.  Needs two different file systems of the same type.
* EROFS: needs to toggle the read-only bit.  This could be done without creating a new file system, if:
  - The user is testing with a dedicated file system (I suppose we could check its mountpoint against common ones, or check that it's size is nearly empty?)
  - The file system supports `mount -ur` and `mount -uw`.  It looks like both ZFS and UFS do.
* EBUSY: this one doesn't actually run any tests on the newly created file system, so it's not a problem.
* EMLINK: I really don't know why this one creates a new file system.  It shouldn't need to.

I confess, I really don't like the option 1 that I suggested above.  It's ugly.  Either pjdfstest should create file systems, or else the user should.  And the rest of pjdfstest relies on the user to create file systems.  So why can't we do these the same way?  Here's a third proposal:

* We change the EMLINK test to use the main file system.
* We serialize the ENOSPC tests, change them to use the main file system, but skip them if the file system is "too big".  Say, larger than 128 MB.
* We use the main file system for EROFS tests, but try to heuristically guess whether it's being used by anybody else.
* We create a new command line argument for the user to provide a second file system for the EXDEV tests.  For ZFS, this could be a separate dataset on the same pool.

**Comment by musikid** [comment]
I tried to convert the EMLINK test to use the main file system, for which `link` returns `EMLINK` if "the number of links to the file named by path1 would exceed {LINK_MAX}". However, {LINK_MAX} is set to a very high value (2^64) on a regular file system, that's why it needs a small memory disk, where {LINK_MAX} will be a reasonable number.
As for the EROFS tests, I'm not sure that implicit behavior is the way to go since we have the configuration file.

**Comment by asomers** [comment]
lol, I'm glad you didn't wait around for that test to finish.  So use the same 128 MB check for the EMLINK tests as for the ENOSPC tests?  And what do you propose for EROFS?  Adding a boolean option to the config file to enable them?

**Comment by musikid** [comment]
Yeah, it was definitely going to take a while!
And yes, I think that the space check is a good idea.
As for EROFS, adding a boolean check to the configuration file while documenting the opt-in nature of these tests should work.

**Comment by musikid** [comment]
I had an idea to avoid having to remount the current file system for EROFS (and also EBUSY?), but I'm not sure if this is a good one. Basically, the idea would be to use a mount with `nullfs` (or bind mount on Linux?), which provides an alternate view of the referred directory tree. It seems to forward all operations to the original file system, and options like read-only can be provided. What do you think?

**Comment by asomers** [comment]
Not going to work.  For one thing, bind on Linux notoriously does _not_ handle the read-only mount option.  It ignores it.  And for another thing, nullfs on FreeBSD has some subtle tricky problems.  It can be made read-only and would probably work for your purposes.  But in that case EROFS would be returned by nullfs.  What we want is for EROFS to be returned by the file system under test instead.

**Comment by musikid** [comment]
I understand, thanks.
