### ISSUE TITLE
11.t | mknod creates device files

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#95]
Should we test for the major/minor numbers? They aren't really used in FreeBSD, but some systems like Linux still use them.

**Comment by asomers** [comment]
Are you talking about adding new tests?  No, let's just focus on the conversion first.

**Comment by musikid** [comment]
Sorry, I wasn't very clear. The tests in this file check if the given major/minor numbers are set. However, since their implementation and usefulness depends on the OS, I was wondering if we should still rewrite them.

**Comment by asomers** [comment]
Yeah, best to preserve them.

**Comment by musikid** [comment]
Alright, I will rewrite then.
